config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :users do
    resources :user_skills, only: [:index, :new, :create, :edit, :update, :destroy]
  end
  resources :skill_categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/skill_category.rb
class SkillCategory < ApplicationRecord
    has_many :user_skills, dependent: :destroy
    has_many :users, through: :user_skills
end

app/models/user.rb
class User < ApplicationRecord
    has_many :user_skills, dependent: :destroy
    has_many :skill_categories, through: :user_skills
end

app/models/user_skill.rb
class UserSkill < ApplicationRecord
  belongs_to :user
  belongs_to :skill_category

  validates :rating, presence: true, inclusion: { in: %w[S A B C D E F] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/skill_categories_controller.rb
class SkillCategoriesController < ApplicationController
    before_action :set_skill_category, only: [:edit, :update, :destroy]

    def index
      @skill_categories = SkillCategory.all
    end
  
    def new
      @skill_category = SkillCategory.new
    end
  
    def create
      @skill_category = SkillCategory.new(skill_category_params)
      if @skill_category.save
        redirect_to skill_categories_path, notice: 'スキルカテゴリを作成しました。'
      else
        render :new
      end
    end
  
    def edit
    end
  
    def update
      if @skill_category.update(skill_category_params)
        redirect_to skill_categories_path, notice: 'スキルカテゴリを更新しました。'
      else
        render :edit
      end
    end
  
    def destroy
      @skill_category.destroy
      redirect_to skill_categories_path, notice: 'スキルカテゴリを削除しました。'
    end
  
    private
  
    def set_skill_category
      @skill_category = SkillCategory.find(params[:id])
    end
  
    def skill_category_params
      params.require(:skill_category).permit(:name)
    end
end

app/controllers/user_skills_controller.rb
class UserSkillsController < ApplicationController
    before_action :set_user
    before_action :set_user_skill, only: [:edit, :update, :destroy]
  
    def index
      @user_skills = @user.user_skills.includes(:skill_category)
    end
  
    def new
      @user_skill = @user.user_skills.new
      @skill_categories = SkillCategory.all
    end
  
    def create
      @user_skill = @user.user_skills.new(user_skill_params)
      if @user_skill.save
        redirect_to user_user_skills_path(@user), notice: 'スキル評価を追加しました。'
      else
        @skill_categories = SkillCategory.all
        render :new
      end
    end
  
    def edit
      @skill_categories = SkillCategory.all
    end
  
    def update
      if @user_skill.update(user_skill_params)
        redirect_to user_user_skills_path(@user), notice: 'スキル評価を更新しました。'
      else
        @skill_categories = SkillCategory.all
        render :edit
      end
    end
  
    def destroy
      @user_skill.destroy
      redirect_to user_user_skills_path(@user), notice: 'スキル評価を削除しました。'
    end
  
    private
  
    def set_user
      @user = User.find(params[:user_id])
    end
  
    def set_user_skill
      @user_skill = @user.user_skills.find(params[:id])
    end
  
    def user_skill_params
      params.require(:user_skill).permit(:skill_category_id, :rating)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]

    def index
      @users = User.all
    end
  
    def show
    end
  
    def new
      @user = User.new
    end
  
    def create
      @user = User.new(user_params)
      if @user.save
        redirect_to users_path, notice: 'ユーザーを作成しました。'
      else
        render :new
      end
    end
  
    def edit
    end
  
    def update
      if @user.update(user_params)
        redirect_to users_path, notice: 'ユーザー情報を更新しました。'
      else
        render :edit
      end
    end
  
    def destroy
      @user.destroy
      redirect_to users_path, notice: 'ユーザーを削除しました。'
    end
  
    private
  
    def set_user
      @user = User.find(params[:id])
    end
  
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/skill_categories_helper.rb
module SkillCategoriesHelper
end

app/helpers/user_skills_helper.rb
module UserSkillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/skill_categories/index.html.erb
<h1>スキルカテゴリ一覧</h1>
<table>
  <thead>
    <tr>
      <th>名前</th>
      <th>操作</th>
    </tr>
  </thead>
  <tbody>
    <% @skill_categories.each do |skill_category| %>
      <tr>
        <td><%= skill_category.name %></td>
        <td>
          <%= link_to '編集', edit_skill_category_path(skill_category) %> |
          <%= link_to '削除', skill_category_path(skill_category), method: :delete, data: { confirm: '本当に削除しますか？' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to '新規カテゴリ作成', new_skill_category_path %>

app/views/skill_categories/new.html.erb
<h1>新規スキルカテゴリ作成</h1>
<%= form_with model: @skill_category, local: true do |form| %>
  <div>
    <%= form.label :name, 'カテゴリ名' %><br>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.submit '作成' %>
  </div>
<% end %>
<%= link_to '戻る', skill_categories_path %>

app/views/user_skills/index.html.erb
<h1><%= @user.name %> のスキル一覧</h1>
<table>
  <thead>
    <tr>
      <th>カテゴリ</th>
      <th>評価</th>
      <th>操作</th>
    </tr>
  </thead>
  <tbody>
    <% @user_skills.each do |user_skill| %>
      <tr>
        <td><%= user_skill.skill_category.name %></td>
        <td><%= user_skill.rating %></td>
        <td>
          <%= link_to '編集', edit_user_user_skill_path(@user, user_skill) %>
          <%= link_to '削除', user_user_skill_path(@user, user_skill), method: :delete, data: { confirm: '本当に削除しますか？' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to '新規スキル追加', new_user_user_skill_path(@user) %>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>
<table>
  <thead>
    <tr>
      <th>名前</th>
      <th>メール</th>
      <th>操作</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td>
          <%= link_to '詳細', user_path(user) %> |
          <%= link_to '編集', edit_user_path(user) %> |
          <%= link_to '削除', user_path(user), method: :delete, data: { confirm: '本当に削除しますか？' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to '新規ユーザー作成', new_user_path %>

app/views/users/new.html.erb
<h1>新規ユーザー作成</h1>
<%= form_with model: @user, local: true do |form| %>
  <div>
    <%= form.label :name, '名前' %><br>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :email, 'メールアドレス' %><br>
    <%= form.email_field :email %>
  </div>
  <div>
    <%= form.submit '作成' %>
  </div>
<% end %>
<%= link_to '戻る', users_path %>

app/views/users/show.html.erb
<h1><%= @user.name %> の詳細</h1>
<p>メールアドレス: <%= @user.email %></p>
<%= link_to '編集', edit_user_path(@user) %> |
<%= link_to '削除', user_path(@user), method: :delete, data: { confirm: '本当に削除しますか？' } %> |
<%= link_to '戻る', users_path %>